# Generated by Django 5.1 on 2025-08-21 14:52

import django.db.models.deletion
import newsletter.abstract_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_alter_article_id_alter_attachment_id_and_more'),
        migrations.swappable_dependency(settings.NEWSLETTER_MESSAGE_MODEL),
        migrations.swappable_dependency(settings.NEWSLETTER_NEWSLETTER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.NEWSLETTER_MESSAGE_MODEL, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=newsletter.abstract_models.attachment_upload_to, verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.NEWSLETTER_MESSAGE_MODEL, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='newsletter',
            field=models.ForeignKey(default=newsletter.abstract_models.get_default_newsletter, on_delete=django.db.models.deletion.CASCADE, to=settings.NEWSLETTER_NEWSLETTER_MODEL, verbose_name='newsletter'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.NEWSLETTER_MESSAGE_MODEL, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='newsletter',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.NEWSLETTER_NEWSLETTER_MODEL, verbose_name='newsletter'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.NEWSLETTER_NEWSLETTER_MODEL, verbose_name='newsletter'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='newsletter_article',
        ),
        migrations.AlterModelTable(
            name='attachment',
            table='newsletter_attachment',
        ),
        migrations.AlterModelTable(
            name='message',
            table='newsletter_message',
        ),
        migrations.AlterModelTable(
            name='newsletter',
            table='newsletter_newsletter',
        ),
        migrations.AlterModelTable(
            name='submission',
            table='newsletter_submission',
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='newsletter_subscription',
        ),
    ]
